# Generated by Django 2.1.4 on 2018-12-18 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('lower_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upper_task', to='task.Task')),
            ],
        ),
    ]
